public interface IDroneCommandInput
{
    /// <summary>
    /// Returns the latest command generated by this input source.
    /// The DroneCommand struct ensures validation (clamping/normalization).
    /// </summary>
    DroneCommand GetCommand();

    /// <summary>
    /// Whether this input is currently active/controlling the drone.
    /// Useful for switching between input sources.
    /// </summary>
    bool IsActive();
}